# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_Xp2mtypisLXxG8Jg2C4M6vjqFJJB8A
"""

def product_numbers():
    num1 = float(input("Введите первое число: "))
    num2 = float(input("Введите второе число: "))

    product = num1 * num2

    print(f'Произведение двух чисел равно {product}')

product_numbers()
#Сложность алгоритма: О(1)